### ISSUE TITLE
No caching

### ISSUE THREAD

**Issue by BramVanroy** [neulab/awesome-align#11]
I am trying to run the script as suggested in the README. I have started it a couple of times, and every time the model needs to be downloaded again and the features need to be recreated. There is no caching at all.

I like this library and its potential (if the results will be reproducible), but its implementation is not very robust and seems implemented in a bit of a hacky, untested, way. This is often the case in research projects (in mine as well), but if the intent is to open-source it and have people use it, it should probably be more robust. I am sure that if you get in touch with the people over at [`transformers`](https://discuss.huggingface.co/) that they can help with better integration in the library and maybe even add the architecture to the library itself! You can tag me there.

**Comment by BramVanroy** [comment]
It seems that --cache_dir needs to be manually set instead of using the default Transformers cache dir, which is a bit odd.

**Comment by zdou0830** [comment]
Thanks for the suggestion!

I intentionally removed dependencies on `transformers` because I personally think it would be easier to develop the tool in this way. I recently changed the default cache dir to a temporarily created one after uploading the package to pypi. Since this has caused confusion I've changed the default cache dir to a permanent one (`~/.cache/torch/awesome-align`, https://github.com/neulab/awesome-align/commit/4c9175b8248690680ed00702e412e8069ba39b20).

Apologies for any inconvenience and contributions are always welcome.

**Comment by BramVanroy** [comment]
If you can tell me which files you changed (I think only modeling.py but I am not sure about the others) and which ones you copied, I can have a look and integrate it better into `transformers` in a PR. 

Why don't you just use the transformers default cache? Now, if someone uses bert-multilingual in transformer-based code and once with awesome-align, the model needs to be downloaded and saved twice because it's in two different locations.

**Comment by zdou0830** [comment]
Thanks! Yes, I think just looking at modeling.py is enough, and it'd be great to integrate it better into `transformers` as long as it doesn't require users to install `transformers`.

**Comment by BramVanroy** [comment]
Why don't you want to use `transformers` as a dependency? Even with a fixed release? That would greatly simplify a lot of your library!
